---
- name: DynamoDB 생성 및 State Lock 구현
  hosts: localhost
  gather_facts: false

  vars:
    table_name: "AnsibleStateLock"
    key_schema:  # 기본키
      - AttributeName: "lockID"
        KeyType: "HASH"
    attribute_definitions:
      - AttributeName: "lockID"
        AttributeType: "S"  # string


  tasks:
    - name: Create DynamoDB table
      community.aws.dynamodb_table:
        name: "{{ table_name }}"
        state: present
        hash_key_name: "lockID"
        hash_key_type: "STRING"
        read_capacity: 5
        write_capacity: 5        
        wait: true
      register: dynamodb_table

    - name: Create state lock item
      shell: >
        aws dynamodb put-item --table-name "{{ table_name }}" --item '{"lockID": {"S": "state_lock"}}'
      register: state_lock_item

    - name: Debug state lock item
      debug:
        var: state_lock_item
