---
- name: Create DynamoDB and Implement State Lock
  hosts: localhost
  gather_facts: false

  vars:
    table_name: "AnsibleStateLock"

  tasks:
    - name: Create DynamoDB table
      community.aws.dynamodb_table:
        name: "{{ table_name }}"
        state: present
        hash_key_name: "lockID"
        hash_key_type: "STRING"
        read_capacity: 5
        write_capacity: 5        
        wait: true
      register: dynamodb_table

    - name: Create state lock item
      shell: >
        aws dynamodb put-item --table-name "{{ table_name }}" --item '{"lockID": {"S": "state_lock"}}' --condition-expression "attribute_not_exists(lockID)"
      register: state_lock_item
      ignore_errors: yes   # 이미 lockID 필드가 있을 경우 생기는 error 무시
