apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: nginx
    environment: production
  annotations:
    description: "Nginx service for the production environment"
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

