apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
spec:
  template:
    metadata:
      labels:
        version: green 
    spec:
      containers:
      - name: nginx
        image: nginx:dev 

