apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service-blue.yaml
- service-green.yaml

patchesStrategicMerge:
- ../overlays/dev/patch_deployment.yaml

