apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: 656714748400.dkr.ecr.ap-northeast-2.amazonaws.com/soldeskweb
    newName: 656714748400.dkr.ecr.ap-northeast-2.amazonaws.com/soldeskweb
    newTag: latest

