apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service-blue.yaml
- service-green.yaml

patches:
- patch: patch_deployment.yaml
  target:
    group: argoproj.io
    kind: Rollout
    version: v1alpha1
    name: nginx-rollout
    namespace: default

