name: Update Kubernetes Manifest

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [update-image]

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Checkout kustomize repository
      uses: actions/checkout@v2
      with:
        repository: byban1/soldesk_Ansible
        ref: main
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        path: soldesk_Ansible

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Get latest image tag from ECR
      run: |
        LATEST_TAG=$(aws ecr describe-images --repository-name soldeskweb --query 'sort_by(imageDetails, &imagePushedAt)[-1].imageTags[0]' --output text)
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

    - name: Update Kubernetes resources
      run: |
        IMAGE_TAG="${{ env.LATEST_TAG }}"
        cd soldesk_Ansible/4.EKS/4-2.Deployment+Service/overlays/dev
        kustomize edit set image nginx=656714748400.dkr.ecr.ap-northeast-2.amazonaws.com/soldeskweb:$IMAGE_TAG
        
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git commit -am "Update image to $IMAGE_TAG" || echo "No changes to commit"
        git push origin main

